# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ^1.16
    - run: make
    - uses: actions/upload-artifact@v2
      with:
        name: podman-wsl.exe
        path: podman-wsl.exe
        if-no-files-found: error
